/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nscompany.pawstop;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Appointment_p extends javax.swing.JFrame {

    /**
     * Creates new form Appointment_p
     */
    public Appointment_p() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        pspe = new javax.swing.JTextField();
        pgen = new javax.swing.JTextField();
        pbreed = new javax.swing.JTextField();
        purr = new javax.swing.JTextField();
        sym = new javax.swing.JTextField();
        apdt = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        oname = new javax.swing.JTextField();
        contact = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1380, 775));
        setMinimumSize(new java.awt.Dimension(1380, 775));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1380, 775));
        jPanel1.setMinimumSize(new java.awt.Dimension(1380, 775));
        jPanel1.setPreferredSize(new java.awt.Dimension(1380, 775));
        jPanel1.setLayout(null);

        jLabel3.setText("Pet Details");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1190, 100, 120, 16);

        jLabel4.setText("Owner Details ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 470, 80, 16);

        jLabel5.setText("Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(220, 80, 32, 16);

        jLabel6.setText("Species");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(220, 130, 50, 16);
        jPanel1.add(dob);
        dob.setBounds(350, 180, 96, 22);

        jLabel7.setText("Date of Birth");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 190, 66, 16);

        jLabel8.setText("Symptoms/Disease");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(230, 260, 101, 16);

        jLabel9.setText("Gender");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(680, 70, 38, 16);

        jLabel10.setText("Breed");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(680, 140, 30, 16);

        jLabel11.setText("purpose of visit");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(660, 200, 81, 16);

        jLabel12.setText("date and time of Appointment ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(620, 270, 164, 16);
        jPanel1.add(pname);
        pname.setBounds(350, 70, 100, 22);
        jPanel1.add(pspe);
        pspe.setBounds(350, 120, 64, 22);
        jPanel1.add(pgen);
        pgen.setBounds(780, 70, 64, 22);
        jPanel1.add(pbreed);
        pbreed.setBounds(790, 140, 64, 22);
        jPanel1.add(purr);
        purr.setBounds(790, 200, 64, 22);
        jPanel1.add(sym);
        sym.setBounds(360, 260, 64, 22);
        jPanel1.add(apdt);
        apdt.setBounds(790, 270, 96, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bb.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 30, 1051, 320);
        jPanel1.add(oname);
        oname.setBounds(790, 440, 64, 22);
        jPanel1.add(contact);
        contact.setBounds(790, 510, 64, 22);
        jPanel1.add(email);
        email.setBounds(790, 590, 64, 22);
        jPanel1.add(add);
        add.setBounds(790, 650, 64, 22);

        jLabel13.setText("Name");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(580, 440, 32, 16);

        jLabel14.setText("Contact ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(570, 510, 45, 16);

        jLabel15.setText("email");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(580, 570, 29, 16);

        jLabel16.setText("address");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(590, 640, 40, 16);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1100, 640, 230, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bb.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(299, 391, 1051, 320);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit
        if(pname.getText().isEmpty()){
             JOptionPane.showMessageDialog(rootPane,"Name cannot be empty");
        }else if(dob.getDate()==null){
            JOptionPane.showMessageDialog(rootPane,"Choose date of birth");
        }else if(pbreed.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Breed cannot ne empty"); 
        }else if(apdt.getDate()==null){
             JOptionPane.showMessageDialog(rootPane,"Choose appointment date and time");
        }else if(pgen.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Gender cannot be empty "); 
        }else if(pspe.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Species cannot be empty");
        }else if(purr.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter purpose of your visit");
        }else if(sym.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Cannot be empty, enter NO if required");
        }else if(oname.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter your name"); 
        }else if(contact.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Enter contacy information"); 
        }else if(email.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Email cannot be empty"); 
        }else if(add.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Address cannot be empty"); 
//        }else{
//             String INSERTDB3="INSERT INTO petdetails( name,gender,species,breed,dob,premed,symp,oname,phoneno,email,address) VALUES(?,?,?,?,?,?,?,?,?,?,?)";
//            try{
//               PreparedStatement ps=cn1.connection.prepareCall(INSERTDB3);
//               ps.setString(1, pname.getText().toString());
//               ps.setString(2, pgen.getText().toString());
//               ps.setString(3, pspe.getText().toString());
//               ps.setString(4, pbreed.getText().toString());
//               ps.setString(5, dob.getDate().toString());
//               ps.setString(3, pspe.getText().toString());
//               ps.setString(3, pspe.getText().toString());
//               
//               Boolean isAdded=ps.execute();
//               JOptionPane.showMessageDialog(rootPane,"Task Assigned");
//               if(isAdded==true){
//                   
//                   System.out.println("Successfully");
//               }
//            }
//             catch(SQLException sqlException){
//                System.out.println("Error Message"+sqlException.getMessage());
//            }
        }
    }//GEN-LAST:event_submit

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Appointment_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Appointment_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Appointment_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Appointment_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Appointment_p().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private com.toedter.calendar.JDateChooser apdt;
    private javax.swing.JTextField contact;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField oname;
    private javax.swing.JTextField pbreed;
    private javax.swing.JTextField pgen;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pspe;
    private javax.swing.JTextField purr;
    private javax.swing.JTextField sym;
    // End of variables declaration//GEN-END:variables
}
