/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.nscompany.pawstop;

import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Lenovo
 */
public class Appointment_a extends javax.swing.JInternalFrame {

    /**
     * Creates new form Appointment_a
     */
    public Appointment_a() {
        initComponents();
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI uii=(BasicInternalFrameUI)this.getUI();
        uii.setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBorder(null);
        setMaximumSize(new java.awt.Dimension(1150, 734));
        setMinimumSize(new java.awt.Dimension(1150, 734));
        setPreferredSize(new java.awt.Dimension(1150, 734));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setText("Owner Details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 410, 80, 40);

        jLabel1.setText("Pet Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 60, 90, 40);

        jDateChooser2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date and Time of Appointment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12), new java.awt.Color(102, 204, 255))); // NOI18N
        jPanel1.add(jDateChooser2);
        jDateChooser2.setBounds(640, 280, 260, 50);

        jDateChooser1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Date of Birth", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12), new java.awt.Color(102, 204, 255))); // NOI18N
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(290, 220, 260, 50);

        jTextField4.setText("-if any-");
        jTextField4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Symptoms ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12), new java.awt.Color(102, 204, 255))); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(290, 290, 260, 40);

        jTextField1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Name", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12), new java.awt.Color(102, 204, 255))); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(290, 100, 260, 40);

        jTextField2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gender", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12), new java.awt.Color(102, 204, 255))); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(640, 100, 260, 40);

        jTextField3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Species", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12), new java.awt.Color(102, 204, 255))); // NOI18N
        jPanel1.add(jTextField3);
        jTextField3.setBounds(290, 160, 260, 41);

        jTextField6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purpose of visit", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12), new java.awt.Color(102, 204, 255))); // NOI18N
        jPanel1.add(jTextField6);
        jTextField6.setBounds(640, 220, 260, 40);

        jTextField8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Breed", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 12), new java.awt.Color(102, 204, 255))); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(640, 160, 260, 41);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bb.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 50, 970, 320);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(530, 450, 270, 30);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(530, 500, 270, 30);
        jPanel1.add(jTextField9);
        jTextField9.setBounds(530, 550, 270, 30);
        jPanel1.add(jTextField10);
        jTextField10.setBounds(530, 600, 270, 30);

        jLabel5.setText("Name");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(400, 456, 32, 20);

        jLabel6.setText("Contact Number");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 510, 90, 16);

        jLabel7.setText("E-mail");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 560, 34, 16);

        jLabel8.setText("Address");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(400, 610, 50, 20);

        jButton1.setText("CONFIRM");
        jButton1.setToolTipText("Book your appointment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(870, 670, 250, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bb.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 390, 810, 320);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -30, 1260, 780);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit
        // TODO add your handling code here:
    }//GEN-LAST:event_submit


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
