/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nscompany.pawstop;

/**
 *
 * @author Lenovo
 */
public class Doc_p extends javax.swing.JFrame {

    /**
     * Creates new form Doc_p
     */
    public Doc_p() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1380, 775));
        jPanel1.setMinimumSize(new java.awt.Dimension(1380, 775));
        jPanel1.setPreferredSize(new java.awt.Dimension(1380, 775));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(52, 139, 227));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Introduction");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 140, 150, 50);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(52, 139, 227));
        jLabel4.setText("Dr. Jane Doe, DVM Veterinarian Doctor  ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 40, 700, 60);

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(52, 139, 227));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Education");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 270, 130, 30);

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(52, 139, 227));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Experience ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(370, 380, 120, 27);

        jLabel7.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(52, 139, 227));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Certifications and Licenses  ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 560, 290, 27);

        jLabel8.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(52, 139, 227));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Professional Memberships ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(280, 620, 270, 27);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setText("<html><p>I am a passionate and dedicated veterinarian with 10 years of experience in providing compassionate care to animals. My expertise lies in [specific areas of veterinary medicine or specialties]. I am committed to staying updated with the latest advancements in veterinary medicine to ensure the highest quality of care for my patients. </p></html> ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(570, 150, 560, 80);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("<html>Doctor of Veterinary Medicine (DVM) <br>- [Name of Veterinary School], [Year of Graduation]<br> Bachelor of Science in Biology/Animal Science<br> - [Name of University], [Year of Graduation]</html>");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(570, 270, 460, 70);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("<html>[Current Position]<br> - [Name of Veterinary Clinic/Hospital], [Location] <br> Provide comprehensive medical care to companion animals, including dogs, cats, and exotic pets.<br> Perform routine examinations, vaccinations, and diagnostic tests.<br> Perform surgeries, including spay/neuter procedures, soft tissue surgeries, and dental procedures.<br> Collaborate with veterinary technicians and support staff to deliver exceptional patient care.</html>");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(570, 380, 590, 140);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel12.setText("Licensed Veterinarian - [State]");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(570, 560, 270, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel13.setText("Member of American Veterinary Medical Association (AVMA) - United States");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(570, 620, 590, 40);

        jButton1.setBackground(new java.awt.Color(102, 204, 255));
        jButton1.setFont(new java.awt.Font("Nirmala UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1170, 20, 160, 28);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jj.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 90, 1170, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Patient p=new Patient();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Doc_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Doc_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Doc_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Doc_p.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Doc_p().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
