/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nscompany.pawstop;


public class Patient extends javax.swing.JFrame {

    public Patient() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        det = new javax.swing.JLabel();
        pre = new javax.swing.JLabel();
        ap = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        con = new javax.swing.JLabel();
        pro = new javax.swing.JLabel();
        deet = new javax.swing.JLabel();
        prescrip = new javax.swing.JLabel();
        app = new javax.swing.JLabel();
        doc = new javax.swing.JLabel();
        cont = new javax.swing.JLabel();
        prof = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1380, 775));
        getContentPane().setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 40, 140, 130);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("USER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 170, 60, 30);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(null);

        det.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        det.setForeground(new java.awt.Color(52, 139, 227));
        det.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        det.setIcon(new javax.swing.ImageIcon(getClass().getResource("/details.png"))); // NOI18N
        det.setText("Details");
        det.setToolTipText("Enter your pet's details");
        det.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        det.setFocusCycleRoot(true);
        det.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        det.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        det.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                detMouseClicked(evt);
            }
        });
        jPanel1.add(det);
        det.setBounds(150, 100, 190, 160);

        pre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pre.setForeground(new java.awt.Color(52, 139, 227));
        pre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prescriptionn.png"))); // NOI18N
        pre.setText("Presriptions\n");
        pre.setToolTipText("View prescription and diagnosis provided by the doctor ");
        pre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pre.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                preMouseClicked(evt);
            }
        });
        jPanel1.add(pre);
        pre.setBounds(510, 100, 150, 160);

        ap.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        ap.setForeground(new java.awt.Color(52, 139, 227));
        ap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appointment.png"))); // NOI18N
        ap.setText("Appointment");
        ap.setToolTipText("Schedule an appointment");
        ap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apMouseClicked(evt);
            }
        });
        jPanel1.add(ap);
        ap.setBounds(840, 100, 170, 160);

        dd.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        dd.setForeground(new java.awt.Color(52, 139, 227));
        dd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doc.png"))); // NOI18N
        dd.setText("Doc Profile");
        dd.setToolTipText("View doctor's profile");
        dd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ddMouseClicked(evt);
            }
        });
        jPanel1.add(dd);
        dd.setBounds(170, 390, 160, 150);

        con.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        con.setForeground(new java.awt.Color(52, 139, 227));
        con.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contact.png"))); // NOI18N
        con.setText("Contact Us");
        con.setToolTipText("Contact the clinic");
        con.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        con.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        con.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                conMouseClicked(evt);
            }
        });
        jPanel1.add(con);
        con.setBounds(530, 380, 130, 160);

        pro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        pro.setForeground(new java.awt.Color(52, 139, 227));
        pro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proff.png"))); // NOI18N
        pro.setText("Profile");
        pro.setToolTipText("View your pet's profile ");
        pro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proMouseClicked(evt);
            }
        });
        jPanel1.add(pro);
        pro.setBounds(860, 376, 140, 170);

        deet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rr.png"))); // NOI18N
        deet.setToolTipText("Enter your pet's details");
        jPanel1.add(deet);
        deet.setBounds(130, 70, 230, 220);

        prescrip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prescrip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rr.png"))); // NOI18N
        prescrip.setToolTipText("View prescription and diagnosis provided by the doctor ");
        jPanel1.add(prescrip);
        prescrip.setBounds(470, 70, 230, 220);

        app.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        app.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rr.png"))); // NOI18N
        app.setToolTipText("Schedule an appointment");
        jPanel1.add(app);
        app.setBounds(800, 70, 240, 220);

        doc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rr.png"))); // NOI18N
        doc.setToolTipText("View doctor's profile");
        jPanel1.add(doc);
        doc.setBounds(140, 350, 220, 220);

        cont.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rr.png"))); // NOI18N
        cont.setToolTipText("Contact the clinic");
        jPanel1.add(cont);
        cont.setBounds(480, 340, 220, 240);

        prof.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rr.png"))); // NOI18N
        prof.setToolTipText("View your pet's profile ");
        jPanel1.add(prof);
        prof.setBounds(810, 350, 230, 220);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(160, 70, 1170, 620);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1170, 20, 50, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 204, 255));
        jLabel5.setText("<html><u>LOGOUT</u></html>");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1210, 20, 70, 30);

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(180, 30, 110, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sss.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1380, 775));
        jLabel2.setMinimumSize(new java.awt.Dimension(1380, 775));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1920, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proMouseClicked
        Profile_p pp =new Profile_p();
        this.dispose();
        pp.setVisible(true);
    }//GEN-LAST:event_proMouseClicked

    private void conMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_conMouseClicked
        Contact_p co =new Contact_p();
        this.dispose();
        co.setVisible(true);
    }//GEN-LAST:event_conMouseClicked

    private void ddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ddMouseClicked
        Doc_p doc =new Doc_p();
        this.dispose();
        doc.setVisible(true);
    }//GEN-LAST:event_ddMouseClicked

    private void apMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apMouseClicked
        Appointment_p a = new Appointment_p();
        this.dispose();
        a.setVisible(true);
    }//GEN-LAST:event_apMouseClicked

    private void preMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_preMouseClicked
        Prescription_p p=new Prescription_p();
        this.dispose();
        p.setVisible(true);
    }//GEN-LAST:event_preMouseClicked

    private void detMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_detMouseClicked
        Details_p d=new Details_p();
        this.dispose();
        d.setVisible(true);
    }//GEN-LAST:event_detMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Log l=new Log();
        this.dispose();
        l.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ap;
    private javax.swing.JLabel app;
    private javax.swing.JLabel con;
    private javax.swing.JLabel cont;
    private javax.swing.JLabel dd;
    private javax.swing.JLabel deet;
    private javax.swing.JLabel det;
    private javax.swing.JLabel doc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel pre;
    private javax.swing.JLabel prescrip;
    private javax.swing.JLabel pro;
    private javax.swing.JLabel prof;
    // End of variables declaration//GEN-END:variables
}
